const PACK_2006 = `http://schemas.openxmlformats.org/package/2006/`,
  OO_2006 = `http://schemas.openxmlformats.org/officeDocument/2006/`,
  DRAWING_ML_2006 = 'http://schemas.openxmlformats.org/drawingml/2006/',
  CONTENT_TYPES_NS = `${PACK_2006}content-types`,
  RELATIONSHIPS_NS = `${PACK_2006}relationships`,
  R_NS = `${OO_2006}relationships`,
  CORE_PROPERTIES_NS = `${PACK_2006}metadata/core-properties`,
  EXTENDED_PROPERTIES_NS = `${OO_2006}extended-properties`,
  CUSTOM_PROPERTIES_NS = `${OO_2006}custom-properties`,
  MATH_NS = `${OO_2006}math`,
  VTYPES_NS = `${OO_2006}docPropsVTypes`,
  DC_NS = `http://purl.org/dc/elements/1.1/`,
  DCTERMS_NS = `http://purl.org/dc/terms/`,
  W_NS = `http://schemas.openxmlformats.org/wordprocessingml/2006/main`,
  SA_NS = 'http://ns.science.ai/ooxml',
  A_NS = `${DRAWING_ML_2006}main`,
  PIC_NS = `${DRAWING_ML_2006}picture`,
  WP_NS = `${DRAWING_ML_2006}wordprocessingDrawing`,
  BIB_NS = `${OO_2006}bibliography`,
  DGM_NS = 'http://schemas.openxmlformats.org/drawingml/2006/diagram',
  DSP_NS = 'http://schemas.microsoft.com/office/drawing/2008/diagram',
  XMLNS_NS = 'http://www.w3.org/2000/xmlns/',
  XML_NS = 'http://www.w3.org/XML/1998/namespace',
  MC_NS = 'http://schemas.openxmlformats.org/markup-compatibility/2006',
  XL_NS = 'http://schemas.openxmlformats.org/spreadsheetml/2006/main',
  X15_NS = 'http://schemas.microsoft.com/office/spreadsheetml/2010/11/main',
  X14AC_NS = 'http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac',
  WPC_NS = 'http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas',
  MO_NS = 'http://schemas.microsoft.com/office/mac/office/2008/main',
  MV_NS = 'urn:schemas-microsoft-com:mac:vml',
  O_NS = 'urn:schemas-microsoft-com:office:office',
  V_NS = 'urn:schemas-microsoft-com:vml',
  WP14_NS =
    'http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing',
  W10_NS = 'urn:schemas-microsoft-com:office:word',
  W14_NS = 'http://schemas.microsoft.com/office/word/2010/wordml',
  W15_NS = 'http://schemas.microsoft.com/office/word/2012/wordml',
  WPG_NS = 'http://schemas.microsoft.com/office/word/2010/wordprocessingGroup',
  WPI_NS = 'http://schemas.microsoft.com/office/word/2010/wordprocessingInk',
  WNE_NS = 'http://schemas.microsoft.com/office/word/2006/wordml',
  WPS_NS = 'http://schemas.microsoft.com/office/word/2010/wordprocessingShape',
  prefixMap = {
    ct: CONTENT_TYPES_NS,
    rels: RELATIONSHIPS_NS,
    r: R_NS,
    cp: CORE_PROPERTIES_NS,
    ep: EXTENDED_PROPERTIES_NS,
    custom: CUSTOM_PROPERTIES_NS,
    vt: VTYPES_NS,
    dc: DC_NS,
    dcterms: DCTERMS_NS,
    w: W_NS,
    m: MATH_NS,
    a: A_NS,
    wp: WP_NS,
    pic: PIC_NS,
    sans: SA_NS,
    xmlns: XMLNS_NS,
    xml: XML_NS,
    b: BIB_NS,
    dgm: DGM_NS,
    dsp: DSP_NS,
    mc: MC_NS,
    xl: XL_NS,
    x15: X15_NS,
    x14ac: X14AC_NS,
    wpc: WPC_NS,
    mo: MO_NS,
    mv: MV_NS,
    o: O_NS,
    v: V_NS,
    wp14: WP14_NS,
    w10: W10_NS,
    w14: W14_NS,
    w15: W15_NS,
    wpg: WPG_NS,
    wpi: WPI_NS,
    wne: WNE_NS,
    wps: WPS_NS
  };

module.exports = {
  CONTENT_TYPES_NS,
  RELATIONSHIPS_NS,
  R_NS,
  CORE_PROPERTIES_NS,
  EXTENDED_PROPERTIES_NS,
  CUSTOM_PROPERTIES_NS,
  VTYPES_NS,
  DC_NS,
  DCTERMS_NS,
  W_NS,
  A_NS,
  MATH_NS,
  SA_NS,
  BIB_NS,
  XMLNS_NS,
  DGM_NS,
  DSP_NS,
  prefixMap
};
